// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJfUSEQp7rSTe0nKMCgoHECXCesfUuIMI',
    appId: '1:310160855148:web:890513ae289e662ee88849',
    messagingSenderId: '310160855148',
    projectId: 'safe-space-geo-app',
    authDomain: 'safe-space-geo-app.firebaseapp.com',
    storageBucket: 'safe-space-geo-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZOs2jPlYh9N6L3gJ1CvniEtM_6QeKV2c',
    appId: '1:310160855148:android:f01a7e5a0f48270ee88849',
    messagingSenderId: '310160855148',
    projectId: 'safe-space-geo-app',
    storageBucket: 'safe-space-geo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS75VhGxDvuNKF_j-JkGNFx4YMTPmjH7o',
    appId: '1:310160855148:ios:424ef6b7451a2aebe88849',
    messagingSenderId: '310160855148',
    projectId: 'safe-space-geo-app',
    storageBucket: 'safe-space-geo-app.firebasestorage.app',
    iosBundleId: 'com.example.safeSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS75VhGxDvuNKF_j-JkGNFx4YMTPmjH7o',
    appId: '1:310160855148:ios:424ef6b7451a2aebe88849',
    messagingSenderId: '310160855148',
    projectId: 'safe-space-geo-app',
    storageBucket: 'safe-space-geo-app.firebasestorage.app',
    iosBundleId: 'com.example.safeSpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJfUSEQp7rSTe0nKMCgoHECXCesfUuIMI',
    appId: '1:310160855148:web:10ec2450f9f3aa5ee88849',
    messagingSenderId: '310160855148',
    projectId: 'safe-space-geo-app',
    authDomain: 'safe-space-geo-app.firebaseapp.com',
    storageBucket: 'safe-space-geo-app.firebasestorage.app',
  );
}
